### PR TITLE
Update message_broker.py

### PR DESCRIPTION
**Pull request by yoavnash**
Adding the HTTP method to the message broker model since it can be important for the application to know.

### CODE REVIEW

**Comment by yoavnash** [comment]
Alternatively, we can add the capability ID instead of the endpoint path and the HTTP method.

**Review by csadorf — APPROVED** [review]
I have one suggestion for a tiny improvement, but otherwise looks good.

**Comment by yoavnash** [comment]
Thank you. I assume I should not merge yet?

**Comment by csadorf** [comment]
> Thank you. I assume I should not merge yet?

I merged it, do you want me to create a new release?

**Comment by pablo-de-andres** [comment]
It is quite well documented [here](https://github.com/materials-marketplace/standard-app-api#for-maintainers)

**Comment by csadorf** [comment]
> That would be helpful (I guess I can do it too?)

Yes, although I'd appreciate if we could coordinate releases for the time being.

**Comment by yoavnash** [comment]
Sure. Should the new version be `0.3.0` or`0.2.1`?

**Comment by csadorf** [comment]
> Sure. Should the new version be `0.3.0` or `0.2.1`?

Unless it is a "fix", any backwards-compatible change should increase the minor version.

**Pull request merged**
